#version: '3.8'
##containers => services
#services:
#  mysql-springboot-container:
#    image: mysql:8.0.35
#    container_name: mysql-springboot-container
#    ports:
#      - 3310:3306
#    volumes:
#      - mysql-springboot-data:/var/lib/mysql
#      - mysql-springboot-config-deamond:/etc/mysql/conf.d
#    networks:
#      backend:
#    environment:
#      MYSQL_USER: sonph
#      MYSQL_PASSWORD: 12345
#      MYSQL_ROOT_PASSWORD: 12345
#      MYSQL_DATABASE: java_docker
#  springboot-docker-container:
#    image: phihongson/springboot-docker:v1.0.0
#    container_name: springboot-docker-container
#    ports:
#      - 8085:8083
#    volumes:
#      - ./:/app
#    networks:
#      - backend
##create network
#networks:
#  backend:
#    external: true
#volumes:
#  mysql-springboot-data:
#  mysql-springboot-config-deamond: